apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50