apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy-pod
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-pod
  template:
    metadata:
      labels:
        app: proxy-pod
    spec:
      containers:
        - name: proxy
          image: kaiii708/proxy:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2m
            requests:
              cpu: 2m