apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  clusterIP: 10.96.0.20
  selector:
    app: server-pod
  ports:
    - protocol: "TCP"
      port: 8001
      targetPort: 8001
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-pod
  template:
    metadata:
      labels:
        app: server-pod
    spec:
      containers:
        - name: server
          image: kaiii708/small-server-demo:latest
          ports:
            - containerPort: 8001
          resources:
            limits: 
              cpu: 0.002m
            requests:
              cpu: 0.001m
